### ISSUE TITLE
程序无法运行the format of ratings data is wrong!

### ISSUE THREAD

**Issue by kugua233** [hongleizhang/Recommender-System#5]
data目录下没有cv文件夹，新建空文档文件后也无法运行，依然提示the format of ratings data is wrong!

**Comment by hongleizhang** [comment]
您好，请认真阅读执行流程，先进行数据集的拆分，使之生成对应的用于交叉验证的多个数据集，而并不是新建cv文件夹，程序会自动生成cv文件夹的。

**Comment by kugua233** [comment]
抱歉没有仔细阅读，已解决。

**Comment by leiliping** [comment]
请问是怎么解决的
